version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9.19
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    parameters:
      distro:
        type: string
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python -V
            curl https://pyenv.run | bash
            pyenv install -s python3
            pyenv global python3
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Display list of files
          command: ls -ltra
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install molecule docker ansible
      - run:
          name: Run Molecule tests
          command: |
            . venv/bin/activate
            PY_COLORS=1 ANSIBLE_FORCE_COLOR=1 MOLECULE_DISTRO=<< parameters.distro >> molecule test

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          matrix:
            parameters:
              distro: ["rockylinux9", "rockylinux8"]
