---
version: 2.1

executors:
  default:
    docker:
      - image: quay.io/hemanth22/rockylinux9:9

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Print Python Verson
          command: |
            dnf install python3-pip wget -y
            python3 -V
            python3 -m pip install requests
      - run:
          name: Provision Pip modules
          command: |
            python3 -m pip install --upgrade pip
      - run:
          name: Provision Ansible modules
          command: |
            python3 -m pip install ansible ansible-lint ansible-core molecule yamllint
            python3 -m pip install -r requirements.txt
      - run:
          name: Yamllint code execution
          command: |
            yamllint .
      - run:
          name: ansible-lint code execution
          command: |
            ansible-lint . | tee >> ansible_lint_error.txt
      - run:
          name: Check build status
          command: |
            touch possible_solutions.txt
            chmod 777 ansible_lint_error.txt possible_solutions.txt
            wget -O GPT3.py https://gistcdn.githack.com/hemanth22/c92ffc14a478abe004dee2d1b3e317c7/raw/dad16f61248886488b6e6e1a40cb1d6b5649cd03/GPT3.py
            python3 GPT3.py
            echo "## Possible solution by ChatGPT on Circle CI Build Error" >> ansible_lint_error.txt
            cat possible_solutions.txt
            cat possible_solutions.txt >> ansible_lint_error.txt
            wget -O create_github_issue.py https://gist.github.com/hemanth22/b1f8ad052685e106820e5d771b58034f/raw
            python3 create_github_issue.py
            ls -ltra
          when: on_fail

workflows:
  ansible_app:
    jobs:
      - build
